automated update

diff --git a/home/.local/bin/copy-file b/home/.local/bin/copy-file
--- a/home/.local/bin/copy-file
+++ b/home/.local/bin/copy-file
@@ -1,3 +1,9 @@
 #!/bin/bash
 
-cat "$1" | xclip -selection clipboard
+if [ -f "$1" ]; then
+	xclip -selection clipboard <"$1"
+	echo "File copied to clipboard."
+else
+	echo "Error: File does not exist."
+	exit 1
+fi
